-- Temporarily disable RLS for testing while we fix the JWT integration
-- DO NOT USE THIS IN PRODUCTION - This is only for debugging

ALTER TABLE clerk_couples DISABLE ROW LEVEL SECURITY;
ALTER TABLE clerk_couple_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE invites DISABLE ROW LEVEL SECURITY;
ALTER TABLE clerk_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE clerk_lists DISABLE ROW LEVEL SECURITY;

-- Add a comment to remind us to re-enable
COMMENT ON TABLE clerk_couples IS 'RLS TEMPORARILY DISABLED FOR DEBUGGING - MUST RE-ENABLE';
COMMENT ON TABLE clerk_couple_members IS 'RLS TEMPORARILY DISABLED FOR DEBUGGING - MUST RE-ENABLE';
COMMENT ON TABLE invites IS 'RLS TEMPORARILY DISABLED FOR DEBUGGING - MUST RE-ENABLE';
COMMENT ON TABLE clerk_notes IS 'RLS TEMPORARILY DISABLED FOR DEBUGGING - MUST RE-ENABLE';
COMMENT ON TABLE clerk_lists IS 'RLS TEMPORARILY DISABLED FOR DEBUGGING - MUST RE-ENABLE';