-- Sprint 5: Agentic Delegation System
-- ====================================
-- Upgrades agent execution from flat runs to execution graphs with checkpoints,
-- adds delegation queue (assign tasks to space members with accept/snooze/reassign),
-- and per-person briefing storage.
-- All tables are ADDITIVE — no existing tables modified or dropped.

-- ─── Agent Executions (v2) ────────────────────────────────────
-- Replaces conceptual reliance on olive_agent_runs with richer
-- execution graph: multi-step, checkpoint-able, resumable.
-- olive_agent_runs remains untouched for backward compatibility.
CREATE TABLE IF NOT EXISTS olive_agent_executions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  space_id UUID REFERENCES olive_spaces(id) ON DELETE SET NULL,

  -- Agent identity
  agent_id TEXT NOT NULL,                        -- skill_id from olive_skills
  agent_name TEXT,                               -- human-readable agent name

  -- Execution graph
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'running', 'paused', 'awaiting_approval', 'completed', 'failed', 'cancelled')),

  -- Steps: ordered array of { step_id, name, status, started_at, completed_at, result, error }
  steps JSONB NOT NULL DEFAULT '[]',
  current_step INT NOT NULL DEFAULT 0,
  total_steps INT NOT NULL DEFAULT 1,

  -- Checkpoint: resumable state blob
  checkpoint JSONB DEFAULT '{}',

  -- Input/output
  input_payload JSONB NOT NULL DEFAULT '{}',      -- what triggered this execution
  output JSONB,                                   -- final result
  error_message TEXT,

  -- Trust integration
  trust_action_id UUID REFERENCES olive_trust_actions(id) ON DELETE SET NULL,
  required_trust_level INT DEFAULT 0,

  -- Timing
  queued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,

  -- Retry / scheduling
  retry_count INT DEFAULT 0,
  max_retries INT DEFAULT 3,
  next_retry_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_agent_exec_user_status
  ON olive_agent_executions (user_id, status, queued_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_exec_space
  ON olive_agent_executions (space_id, status)
  WHERE space_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_agent_exec_agent
  ON olive_agent_executions (agent_id, user_id, queued_at DESC);

-- ─── Delegations ──────────────────────────────────────────────
-- Task delegation between space members. Olive can suggest delegations,
-- or users can delegate directly. Delegatees can accept, snooze, or reassign.
CREATE TABLE IF NOT EXISTS olive_delegations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  space_id UUID NOT NULL REFERENCES olive_spaces(id) ON DELETE CASCADE,

  -- What is being delegated
  note_id UUID,                                  -- linked note/task (if applicable)
  title TEXT NOT NULL,                           -- delegation title
  description TEXT,                              -- what needs to be done
  priority TEXT DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),

  -- Who
  delegated_by TEXT NOT NULL,                    -- Clerk user ID of delegator
  delegated_to TEXT NOT NULL,                    -- Clerk user ID of delegatee
  suggested_by TEXT DEFAULT 'user',              -- 'user', 'olive', 'agent'

  -- Status flow: pending → accepted/snoozed/reassigned/declined/completed
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted', 'snoozed', 'reassigned', 'declined', 'completed', 'cancelled')),

  -- Snooze
  snoozed_until TIMESTAMPTZ,

  -- Reassignment chain
  reassigned_to TEXT,                            -- if reassigned, new delegatee
  reassign_reason TEXT,

  -- Response
  response_note TEXT,                            -- delegatee's response message
  responded_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,

  -- Agent context (if Olive suggested this)
  agent_execution_id UUID REFERENCES olive_agent_executions(id) ON DELETE SET NULL,
  reasoning TEXT,                                -- why Olive suggested this delegation

  -- Notification tracking
  notified_via TEXT[] DEFAULT '{}',              -- ['app', 'whatsapp', 'email']
  last_notified_at TIMESTAMPTZ,
  reminder_count INT DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_delegations_delegatee
  ON olive_delegations (delegated_to, status, created_at DESC)
  WHERE status IN ('pending', 'accepted', 'snoozed');

CREATE INDEX IF NOT EXISTS idx_delegations_delegator
  ON olive_delegations (delegated_by, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_delegations_space
  ON olive_delegations (space_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_delegations_note
  ON olive_delegations (note_id)
  WHERE note_id IS NOT NULL;

-- ─── Briefings ────────────────────────────────────────────────
-- Per-person daily briefings generated by Olive.
-- Each briefing is personalized based on the recipient's role, tasks, and space context.
CREATE TABLE IF NOT EXISTS olive_briefings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  space_id UUID REFERENCES olive_spaces(id) ON DELETE SET NULL,

  -- Briefing type
  briefing_type TEXT NOT NULL DEFAULT 'daily'
    CHECK (briefing_type IN ('daily', 'weekly', 'on_demand', 'delegation_summary')),

  -- Content
  title TEXT NOT NULL,
  summary TEXT NOT NULL,                         -- main briefing text (markdown)
  sections JSONB NOT NULL DEFAULT '[]',          -- structured: [{ heading, items: [{ text, note_id?, priority? }] }]

  -- Metadata
  covers_from TIMESTAMPTZ,                       -- time range this briefing covers
  covers_to TIMESTAMPTZ,
  task_count INT DEFAULT 0,                      -- tasks mentioned
  delegation_count INT DEFAULT 0,                -- delegations mentioned

  -- Status
  delivered_via TEXT[] DEFAULT '{}',              -- ['app', 'whatsapp']
  read_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_briefings_user_recent
  ON olive_briefings (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_briefings_user_type
  ON olive_briefings (user_id, briefing_type, created_at DESC);

-- ─── Delegation Activity Trigger ──────────────────────────────
-- Auto-log delegation events to space_activity for the activity feed.
CREATE OR REPLACE FUNCTION trg_log_delegation_activity()
RETURNS TRIGGER AS $$
BEGIN
  -- Log new delegations
  IF TG_OP = 'INSERT' THEN
    INSERT INTO space_activity (space_id, user_id, action, entity_type, entity_id, metadata)
    VALUES (
      NEW.space_id,
      NEW.delegated_by,
      'delegated',
      'delegation',
      NEW.id,
      jsonb_build_object('title', NEW.title, 'delegated_to', NEW.delegated_to, 'priority', NEW.priority)
    );
  END IF;

  -- Log status changes
  IF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status THEN
    INSERT INTO space_activity (space_id, user_id, action, entity_type, entity_id, metadata)
    VALUES (
      NEW.space_id,
      NEW.delegated_to,
      CASE NEW.status
        WHEN 'accepted' THEN 'accepted_delegation'
        WHEN 'declined' THEN 'declined_delegation'
        WHEN 'reassigned' THEN 'reassigned_delegation'
        WHEN 'completed' THEN 'completed_delegation'
        WHEN 'snoozed' THEN 'snoozed_delegation'
        ELSE 'updated_delegation'
      END,
      'delegation',
      NEW.id,
      jsonb_build_object('title', NEW.title, 'old_status', OLD.status, 'new_status', NEW.status)
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_delegation_activity
  AFTER INSERT OR UPDATE ON olive_delegations
  FOR EACH ROW
  EXECUTE FUNCTION trg_log_delegation_activity();

-- ─── Delegation Updated_at Trigger ────────────────────────────
CREATE OR REPLACE FUNCTION trg_delegation_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_delegation_set_updated_at
  BEFORE UPDATE ON olive_delegations
  FOR EACH ROW
  EXECUTE FUNCTION trg_delegation_updated_at();

-- ─── RLS Policies ─────────────────────────────────────────────
ALTER TABLE olive_agent_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE olive_delegations ENABLE ROW LEVEL SECURITY;
ALTER TABLE olive_briefings ENABLE ROW LEVEL SECURITY;

-- Agent executions: users see their own
CREATE POLICY "Users see own agent executions"
  ON olive_agent_executions FOR SELECT
  USING (user_id = (auth.jwt() ->> 'sub'));

CREATE POLICY "Service role manages agent executions"
  ON olive_agent_executions FOR ALL
  USING (true) WITH CHECK (true);

-- Delegations: visible to delegator, delegatee, and space members
CREATE POLICY "Users see delegations they're involved in"
  ON olive_delegations FOR SELECT
  USING (
    delegated_by = (auth.jwt() ->> 'sub')
    OR delegated_to = (auth.jwt() ->> 'sub')
    OR reassigned_to = (auth.jwt() ->> 'sub')
  );

CREATE POLICY "Users can update delegations assigned to them"
  ON olive_delegations FOR UPDATE
  USING (
    delegated_to = (auth.jwt() ->> 'sub')
    OR reassigned_to = (auth.jwt() ->> 'sub')
  );

CREATE POLICY "Users can create delegations in their spaces"
  ON olive_delegations FOR INSERT
  WITH CHECK (
    delegated_by = (auth.jwt() ->> 'sub')
  );

CREATE POLICY "Service role manages delegations"
  ON olive_delegations FOR ALL
  USING (true) WITH CHECK (true);

-- Briefings: users see their own
CREATE POLICY "Users see own briefings"
  ON olive_briefings FOR SELECT
  USING (user_id = (auth.jwt() ->> 'sub'));

CREATE POLICY "Service role manages briefings"
  ON olive_briefings FOR ALL
  USING (true) WITH CHECK (true);

-- ─── Add delegation message type to engagement events ─────────
-- (Extending the CHECK constraint with new event types)
ALTER TABLE olive_engagement_events DROP CONSTRAINT IF EXISTS olive_engagement_events_event_type_check;
ALTER TABLE olive_engagement_events ADD CONSTRAINT olive_engagement_events_event_type_check
  CHECK (event_type IN (
    'message_sent', 'message_responded',
    'proactive_accepted', 'proactive_ignored', 'proactive_rejected',
    'action_approved', 'action_rejected',
    'task_completed', 'note_created', 'session_start',
    -- New Sprint 5 event types
    'delegation_created', 'delegation_accepted', 'delegation_declined',
    'delegation_completed', 'delegation_snoozed', 'delegation_reassigned',
    'briefing_read'
  ));
